### ISSUE TITLE
Find a better way to get more geographical coordinates

### ISSUE THREAD

**Issue by maelle** [masalmon/india_trains#2]
The comparison of names between the train timetable and the OSM data could be better. How, I don't know. :-)

**Comment by kartiek** [comment]
Hi! I might have a solution to this. 
Pls see http://www.kartiek.in/railway-network-india/ and https://developers.google.com/maps/documentation/geocoding/intro#RegionCodes

**Comment by maelle** [comment]
This is AWESOME!

You still get a few wrong coordinates,  Don't you ? It might be possible to use the distance information from the train timetable (comparing the provided distance with the one you get from using the imputed coordinates ) + using OSM data and phonetic spelling comparison of names between osm and the timetable for finding some stations?

**Comment by maelle** [comment]
But really, your post made me happy, nice job!
